# Generated by Django 2.0.6 on 2018-07-18 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='guiding_fields',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='learning_fields',
        ),
    ]
