# Generated by Django 2.0.6 on 2018-08-03 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180718_0257'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subscribe_to_newsletter',
            field=models.BooleanField(default=True),
        ),
    ]
