# Generated by Django 2.0.7 on 2018-09-30 16:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0002_telegramtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramtoken',
            name='telegram_user_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
