# Generated by Django 2.0.6 on 2018-08-26 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180826_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='complete_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
