# Generated by Django 2.1 on 2018-08-29 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_team'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team',
        ),
    ]
