# Generated by Django 2.0.6 on 2018-08-08 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companions', '0001_initial'),
        ('users', '0006_auto_20180804_0223'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='applications',
            field=models.ManyToManyField(blank=True, to='companions.Application'),
        ),
    ]
