# Generated by Django 2.0.6 on 2018-08-04 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20180804_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_publicity',
            field=models.BooleanField(default=True),
        ),
    ]
