# Generated by Django 2.0.6 on 2018-08-10 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_profile_email_publicity'),
        ('users', '0007_profile_applications'),
    ]

    operations = [
    ]
