# Generated by Django 2.0.6 on 2018-08-10 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companions', '0001_initial'),
        ('users', '0010_merge_20180810_0533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='applications',
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='applications',
            field=models.ManyToManyField(blank=True, to='companions.Application'),
        ),
    ]
