# Generated by Django 2.1 on 2018-08-29 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamUserRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CREATOR', 'CREATOR'), ('MANAGER', 'MANAGER'), ('MEMBER', 'MEMBER')], max_length=30)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.Team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='teampersonrelation',
            name='person',
        ),
        migrations.RemoveField(
            model_name='teampersonrelation',
            name='team',
        ),
        migrations.DeleteModel(
            name='TeamPersonRelation',
        ),
    ]
