# Generated by Django 2.0.9 on 2018-11-11 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0005_profile_telegram_user_id'),
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamuserrelation',
            name='user',
        ),
        migrations.AddField(
            model_name='teamuserrelation',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.Profile'),
            preserve_default=False,
        ),
    ]
