# Generated by Django 2.0.7 on 2018-09-21 10:49

from django.db import migrations
import enumfields.fields
import team.models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamuserrelation',
            name='type',
            field=enumfields.fields.EnumField(default='CREATOR', enum=team.models.TeamUserRelationType, max_length=1000),
        ),
    ]
