# Generated by Django 2.0.7 on 2018-09-19 05:50

from django.db import migrations
import enumfields.fields
import team.models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_auto_20180829_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamuserrelation',
            name='type',
            field=enumfields.fields.EnumField(enum=team.models.TeamUserRelationType, max_length=100),
        ),
    ]
