# Generated by Django 2.0.7 on 2018-09-19 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_auto_20180919_0550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamuserrelation',
            name='type',
        ),
    ]
