# Generated by Django 2.0.7 on 2018-09-19 06:01

from django.db import migrations
import enumfields.fields
import team.models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_remove_teamuserrelation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamuserrelation',
            name='type',
            field=enumfields.fields.EnumField(default='CREATOR', enum=team.models.TeamUserRelationType, max_length=100),
        ),
    ]
