# Generated by Django 2.0.7 on 2018-09-19 07:23

from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields
import taxonomy.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_fa', models.CharField(blank=True, max_length=255, null=True)),
                ('taxonomy_type', enumfields.fields.EnumField(default='SUBJECT', enum=taxonomy.models.TaxonomyType, max_length=100)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='TermRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', enumfields.fields.EnumField(default='CHILD_OF', enum=taxonomy.models.TermRealtionType, max_length=100)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='taxonomy.Term')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source', to='taxonomy.Term')),
            ],
        ),
    ]
