# Generated by Django 2.0.7 on 2018-09-21 10:49

from django.db import migrations
import enumfields.fields
import taxonomy.models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='taxonomy_type',
            field=enumfields.fields.EnumField(default='SUBJECT', enum=taxonomy.models.TaxonomyType, max_length=1000),
        ),
        migrations.AlterField(
            model_name='termrelation',
            name='type',
            field=enumfields.fields.EnumField(default='CHILD_OF', enum=taxonomy.models.TermRealtionType, max_length=1000),
        ),
    ]
