# Generated by Django 2.0.7 on 2018-09-17 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='title_fa',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
