# Generated by Django 2.0.9 on 2018-11-02 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
