# Generated by Django 2.0.9 on 2018-11-02 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0002_auto_20181102_1358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='term',
            name='title_fa',
        ),
    ]
