# Generated by Django 2.0.7 on 2018-09-19 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0002_auto_20180917_0443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='term',
            name='taxonomy_type',
        ),
        migrations.RemoveField(
            model_name='termrelation',
            name='type',
        ),
    ]
