# Generated by Django 2.0.6 on 2018-07-29 07:56

from django.db import migrations, models
import taxonomy.models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0002_auto_20180719_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='taxonomy_type',
            field=models.CharField(choices=[('learning_field', 'LEARNING_FIELD'), ('subject', 'SUBJECT')], default=taxonomy.models.TaxonomyType('subject'), max_length=30),
        ),
        migrations.AlterField(
            model_name='termrelation',
            name='type',
            field=models.CharField(choices=[('child_of', 'CHILD_OF')], max_length=30),
        ),
    ]
