# Generated by Django 2.0.7 on 2018-10-02 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_auto_20181001_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramtoken',
            name='telegram_user_id',
            field=models.IntegerField(unique=True),
        ),
    ]
