# Generated by Django 2.0.7 on 2018-10-03 09:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bot', '0003_auto_20181002_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramtoken',
            name='telegram_user_id',
            field=models.IntegerField(),
        ),
    ]
