# Generated by Django 2.0.9 on 2018-10-21 16:00

import bot.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bot', '0004_auto_20181003_0955'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramProfile',
            fields=[
                ('telegram_user_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('verify_token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('menu_state', enumfields.fields.EnumField(default='START', enum=bot.models.MenuState, max_length=10)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telegram_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
