# Generated by Django 2.0.9 on 2018-10-24 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_auto_20181023_1957'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TelegramToken',
        ),
    ]
