# Generated by Django 2.0.9 on 2018-11-02 14:26

import bot.models
from django.db import migrations
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_auto_20181024_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramprofile',
            name='menu_state',
            field=enumfields.fields.EnumField(default='START', enum=bot.models.MenuState, max_length=1000),
        ),
        migrations.AlterField(
            model_name='telegramuserinput',
            name='key',
            field=enumfields.fields.EnumField(enum=bot.models.TelegramUserInputKeys, max_length=1000),
        ),
    ]
