# Generated by Django 2.0.9 on 2018-11-02 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bot', '0009_auto_20181102_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramprofile',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='telegram_profile', to='users.Profile'),
        ),
    ]
