# Generated by Django 2.0.9 on 2018-11-07 07:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bot', '0010_auto_20181102_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramprofile',
            name='pv_enabled',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
