# Generated by Django 2.0.7 on 2018-09-19 07:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learning_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_field', to='taxonomy.Term')),
                ('student', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mentoring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentor_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_info', to='learning.LearningInfo')),
                ('student_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_info', to='learning.LearningInfo')),
            ],
        ),
        migrations.CreateModel(
            name='MentoringInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('road_map', models.TextField(blank=True, null=True)),
                ('mentor', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('mentoring_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentoring_field', to='taxonomy.Term')),
            ],
        ),
        migrations.CreateModel(
            name='QualificationInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=4)),
                ('qualified_student_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualified_student_info', to='learning.LearningInfo')),
                ('qualifier', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
