# Generated by Django 2.0.9 on 2018-11-02 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learninginfo',
            name='learning_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_fields',
                                    to='taxonomy.Term'),
        ),
        migrations.AlterField(
            model_name='learninginfo',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='skills',
                                    to='users.Profile'),
        ),
        migrations.AlterField(
            model_name='mentoringinfo',
            name='mentor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.Profile'),
        ),
        migrations.AlterField(
            model_name='mentoringinfo',
            name='mentoring_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentoring_fields',
                                    to='taxonomy.Term'),
        ),
    ]
