# Generated by Django 2.0.6 on 2018-08-11 21:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentoring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentor_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_info', to='learning.LearningInfo')),
                ('student_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_info', to='learning.LearningInfo')),
            ],
        ),
        migrations.CreateModel(
            name='QualificationInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=4)),
                ('qualified_student_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualified_student_info', to='learning.LearningInfo')),
                ('qualifier', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
