# Generated by Django 2.0.6 on 2018-07-18 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0001_initial'),
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentoringinfo',
            name='road_map',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='learninginfo',
            name='learning_field',
        ),
        migrations.AddField(
            model_name='learninginfo',
            name='learning_field',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='learning_field', to='taxonomy.Term'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='mentoringinfo',
            name='mentoring_field',
        ),
        migrations.AddField(
            model_name='mentoringinfo',
            name='mentoring_field',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mentoring_field', to='taxonomy.Term'),
            preserve_default=False,
        ),
    ]
