# Generated by Django 2.0.7 on 2018-10-06 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignContentRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_campaign', to='campaigns.Campaign')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_content', to='content.Content')),
            ],
        ),
    ]
