# Generated by Django 2.0.7 on 2018-09-13 17:48

import campaigns.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companions', '0001_initial'),
        ('taxonomy', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('type', models.CharField(choices=[('WORK', 'WORK'), ('MENTORING', 'MENTORING'), ('STUDY', 'STUDY'), ('SALES', 'SALES')], max_length=30)),
                ('image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=campaigns.models.campaign_image_upload_location, width_field='width_field')),
                ('height_field', models.IntegerField(default=0)),
                ('width_field', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('application', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='companions.Application')),
            ],
        ),
        migrations.CreateModel(
            name='CampaignPartyRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('type', models.CharField(choices=[('CREATOR', 'CREATOR'), ('MANAGER', 'MANAGER'), ('MEMBER', 'MEMBER')], max_length=30)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.Campaign')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='CampaignTermRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('SUBJECT', 'SUBJECT')], max_length=30)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign', to='campaigns.Campaign')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term', to='taxonomy.Term')),
            ],
        ),
    ]
