# Generated by Django 2.0.9 on 2018-10-07 05:50

import campaigns.models
from django.db import migrations
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_campaigncontentrelation'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigncontentrelation',
            name='type',
            field=enumfields.fields.EnumField(default='CREATED_ON', enum=campaigns.models.CampaignContentRelationType, max_length=100),
        ),
    ]
