# Generated by Django 2.0.7 on 2018-09-14 08:10

import campaigns.models
from django.db import migrations
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_campaign_campaignpartyrelation_campaigntermrelation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='type',
            field=enumfields.fields.EnumField(enum=campaigns.models.CampaignType, max_length=1),
        ),
    ]
