# Generated by Django 2.0.7 on 2018-09-21 10:41

import campaigns.models
from django.db import migrations
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_remove_campaign_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='type',
            field=enumfields.fields.EnumField(enum=campaigns.models.CampaignType, max_length=1000),
        ),
    ]
