# Generated by Django 2.0.9 on 2018-11-02 14:28

import enumfields.fields
from django.db import migrations

import campaigns.models


class Migration(migrations.Migration):
    dependencies = [
        ('campaigns', '0003_campaigncontentrelation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigncontentrelation',
            name='type',
            field=enumfields.fields.EnumField(default='CREATED_ON', enum=campaigns.models.CampaignContentRelationType,
                                              max_length=1000),
        ),
        migrations.AlterField(
            model_name='campaignpartyrelation',
            name='type',
            field=enumfields.fields.EnumField(enum=campaigns.models.CampaignPartyRelationType, max_length=1000),
        ),
        migrations.AlterField(
            model_name='campaigntermrelation',
            name='type',
            field=enumfields.fields.EnumField(enum=campaigns.models.CampaignTermRealtionType, max_length=1000),
        ),
    ]
