# Generated by Django 2.0.9 on 2018-11-06 21:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('campaigns', '0004_auto_20181102_1428'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='title',
            new_name='name',
        ),
    ]
