# Generated by Django 2.0.7 on 2018-09-17 07:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_auto_20180914_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='end_time',
            field=models.DateField(default=datetime.datetime(2018, 9, 17, 7, 13, 35, 311841, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campaign',
            name='start_time',
            field=models.DateField(default=datetime.datetime(2018, 9, 17, 7, 13, 45, 92659, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
