# Generated by Django 2.0.7 on 2018-09-21 10:49

import campaigns.models
from django.db import migrations, models
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_auto_20180921_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='title',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='campaignpartyrelation',
            name='type',
            field=enumfields.fields.EnumField(enum=campaigns.models.CampaignPartyRelationType, max_length=1000),
        ),
        migrations.AlterField(
            model_name='campaigntermrelation',
            name='type',
            field=enumfields.fields.EnumField(enum=campaigns.models.CampaignTermRealtionType, max_length=1000),
        ),
    ]
