# Generated by Django 2.0.9 on 2018-11-06 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_auto_20181106_2120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='name',
            new_name='title',
        ),
    ]
