# Generated by Django 2.0.9 on 2018-11-06 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0006_auto_20181106_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='duration_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='end_time',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='start_time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
