# Generated by Django 2.0.7 on 2018-09-19 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0007_auto_20180918_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='author',
        ),
        migrations.RemoveField(
            model_name='report',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='report',
            name='task',
        ),
        migrations.RemoveField(
            model_name='task',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='task',
            name='campaign',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
