# Generated by Django 2.0.9 on 2018-11-09 09:26

import campaigns.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0007_auto_20181106_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='banner_height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaign',
            name='banner_image',
            field=models.ImageField(blank=True, height_field='banner_height_field', null=True, upload_to=campaigns.models.campaign_image_upload_location, width_field='banner_width_field'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='banner_width_field',
            field=models.IntegerField(default=0),
        ),
    ]
