# Generated by Django 2.0.7 on 2018-09-21 11:24

import django.db.models.deletion
import enumfields.fields
from django.conf import settings
from django.db import migrations, models

import content.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('type',
                 enumfields.fields.EnumField(default='ARTICLE', enum=content.models.ContentType, max_length=1000)),
                ('main_type',
                 enumfields.fields.EnumField(default='TEXT', enum=content.models.MainContentType, max_length=1000)),
                ('visibility',
                 enumfields.fields.EnumField(default='PUBLIC', enum=content.models.ContentVisibility, max_length=1000)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('image', models.ImageField(blank=True, height_field='height_field', null=True,
                                            upload_to=content.models.content_image_upload_location,
                                            width_field='width_field')),
                ('height_field', models.IntegerField(default=0)),
                ('width_field', models.IntegerField(default=0)),
                ('content', models.TextField()),
                ('flash_note', models.TextField(blank=True, null=True)),
                ('draft', models.BooleanField(default=False)),
                ('publish', models.DateField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                             to=settings.AUTH_USER_MODEL)),
                ('down_voters',
                 models.ManyToManyField(blank=True, related_name='down_voters', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                              related_name='subject', to='taxonomy.Term')),
                ('terms', models.ManyToManyField(blank=True, related_name='terms', to='taxonomy.Term')),
                (
                'up_voters', models.ManyToManyField(blank=True, related_name='up_voters', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ContentRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', enumfields.fields.EnumField(default='COMMENTED_ON', enum=content.models.ContentRelationType,
                                                     max_length=1000)),
                ('destination',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination',
                                   to='content.Content')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source',
                                             to='content.Content')),
            ],
        ),
    ]
