# Generated by Django 2.0.6 on 2018-08-10 05:47

import content.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taxonomy', '__first__'),
        ('companions', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('type', models.CharField(choices=[('article', 'ARTICLE'), ('report', 'REPORT'), ('problem', 'PROBLEM'), ('solution', 'SOLUTION'), ('question', 'QUESTION'), ('answer', 'ANSWER'), ('comment', 'COMMENT')], max_length=30)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=content.models.content_image_upload_location, width_field='width_field')),
                ('height_field', models.IntegerField(default=0)),
                ('width_field', models.IntegerField(default=0)),
                ('content', models.TextField()),
                ('draft', models.BooleanField(default=False)),
                ('publish', models.DateField()),
                ('read_time', models.IntegerField(default=0)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='companions.Application')),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject', to='taxonomy.Term')),
                ('terms', models.ManyToManyField(blank=True, related_name='terms', to='taxonomy.Term')),
            ],
        ),
        migrations.CreateModel(
            name='ContentRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('commented_on', 'COMMENTED_ON')], max_length=30)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='content.Content')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source', to='content.Content')),
            ],
        ),
    ]
