# Generated by Django 2.0.6 on 2018-07-29 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='note',
        ),
        migrations.AlterField(
            model_name='content',
            name='title',
            field=models.CharField(max_length=1000),
        ),
    ]
