# Generated by Django 2.0.9 on 2018-10-23 10:24

from django.db import migrations, models

import content.models


class Migration(migrations.Migration):
    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='attachment',
            field=models.ImageField(blank=True, height_field='height_field', null=True,
                                    upload_to=content.models.content_attachment_upload_location,
                                    width_field='width_field'),
        ),
    ]
