# Generated by Django 2.0.6 on 2018-08-10 15:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='down_voters',
            field=models.ManyToManyField(blank=True, related_name='down_voters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='content',
            name='up_voters',
            field=models.ManyToManyField(blank=True, related_name='up_voters', to=settings.AUTH_USER_MODEL),
        ),
    ]
