# Generated by Django 2.0.9 on 2018-10-23 11:50

import content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_content_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=content.models.content_attachment_upload_location),
        ),
    ]
