# Generated by Django 2.0.6 on 2018-07-29 07:48

import content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20180729_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='type',
            field=models.CharField(choices=[(content.models.ContentType('article'), 'article'), (content.models.ContentType('report'), 'report'), (content.models.ContentType('problem'), 'problem'), (content.models.ContentType('solution'), 'solution'), (content.models.ContentType('question'), 'question'), (content.models.ContentType('answer'), 'answer'), (content.models.ContentType('comment'), 'comment')], max_length=30),
        ),
    ]
