# Generated by Django 2.0.6 on 2018-07-22 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0002_auto_20180719_2207'),
        ('content', '0002_content_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='terms',
            field=models.ManyToManyField(blank=True, related_name='terms', to='taxonomy.Term'),
        ),
    ]
