# Generated by Django 2.0.6 on 2018-07-29 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20180729_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='type',
            field=models.CharField(choices=[('article', 'ARTICLE'), ('report', 'REPORT'), ('problem', 'PROBLEM'), ('solution', 'SOLUTION'), ('question', 'QUESTION'), ('answer', 'ANSWER'), ('comment', 'COMMENT')], max_length=30),
        ),
        migrations.AlterField(
            model_name='contentrelation',
            name='type',
            field=models.CharField(choices=[('commented_on', 'COMMENTED_ON')], max_length=30),
        ),
    ]
