# Generated by Django 2.0.6 on 2018-08-26 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_content_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='type',
            field=models.CharField(choices=[('article', 'ARTICLE'), ('report', 'REPORT'), ('problem', 'PROBLEM'), ('solution', 'SOLUTION'), ('question', 'QUESTION'), ('answer', 'ANSWER'), ('comment', 'COMMENT'), ('story', 'STORY')], max_length=30),
        ),
    ]
