# Generated by Django 2.0.6 on 2018-08-10 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_content_application'),
        ('content', '0004_auto_20180729_0756'),
    ]

    operations = [
    ]
