# Generated by Django 2.0.7 on 2018-09-17 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_auto_20180826_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='read_time',
        ),
    ]
