# Generated by Django 2.0.7 on 2018-09-17 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_remove_content_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='height_field',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='width_field',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
