# Generated by Django 2.0.9 on 2018-11-13 21:56

import content.models
from django.db import migrations, models
import django.utils.timezone
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_auto_20181113_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='publish',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='content',
            name='type',
            field=enumfields.fields.EnumField(blank=True, default='ARTICLE', enum=content.models.ContentType, max_length=1000),
        ),
        migrations.AlterField(
            model_name='content',
            name='visibility',
            field=enumfields.fields.EnumField(blank=True, default='PUBLIC', enum=content.models.ContentVisibility, max_length=1000),
        ),
    ]
