# Generated by Django 2.0.9 on 2018-11-16 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_auto_20181113_2156'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='content',
            unique_together={('slug', 'type')},
        ),
    ]
