# Generated by Django 2.0.7 on 2018-09-19 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_auto_20180917_0610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='type',
        ),
        migrations.RemoveField(
            model_name='content',
            name='visibility',
        ),
        migrations.RemoveField(
            model_name='contentrelation',
            name='type',
        ),
        migrations.AddField(
            model_name='content',
            name='flash_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
