# Generated by Django 2.0.7 on 2018-09-19 05:46

import content.models
from django.db import migrations, models
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_auto_20180917_0610'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='flash_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='main_type',
            field=enumfields.fields.EnumField(default='TEXT', enum=content.models.MainContentType, max_length=1),
        ),
        migrations.AlterField(
            model_name='content',
            name='type',
            field=enumfields.fields.EnumField(default='ARTICLE', enum=content.models.ContentType, max_length=1),
        ),
        migrations.AlterField(
            model_name='content',
            name='visibility',
            field=enumfields.fields.EnumField(default='PUBLIC', enum=content.models.ContentVisibility, max_length=1),
        ),
        migrations.AlterField(
            model_name='contentrelation',
            name='type',
            field=enumfields.fields.EnumField(enum=content.models.ContentRealtionType, max_length=1),
        ),
    ]
