# Generated by Django 2.0.7 on 2018-09-19 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_auto_20180919_0546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='main_type',
        ),
        migrations.RemoveField(
            model_name='content',
            name='type',
        ),
        migrations.RemoveField(
            model_name='content',
            name='visibility',
        ),
    ]
